Not Found: /index
Internal Server Error: /index
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 389, in resolve
    raise Resolver404({'path': path})
django.core.urlresolvers.Resolver404: {'path': 'index'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 86, in get_exception_response
    callback, param_dict = resolver.resolve_error_handler(status_code)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 415, in resolve_error_handler
    callback = getattr(self.urlconf_module, 'handler%s' % view_type, None)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 25
    url(r'^user/', include('user.urls', namespace='user')),
      ^
SyntaxError: invalid syntax
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 7, in <module>
    from user import views as user_views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 23, in <module>
    class RegistrationView(FormValidMessageMixin, CreateView):
NameError: name 'CreateView' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 7, in <module>
    from user import views as user_views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 24, in <module>
    class RegistrationView(FormValidMessageMixin, CreateView):
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 27, in RegistrationView
    form_class = UserCreateForm
NameError: name 'UserCreateForm' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 7, in <module>
    from user import views as user_views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 13, in <module>
    from user.forms import UserCreateForm
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/forms.py", line 6, in <module>
    from djangular.forms import NgFormValidationMixin
ImportError: No module named 'djangular.forms'
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 7, in <module>
    from user import views as user_views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 25, in <module>
    class RegistrationView(FormValidMessageMixin, CreateView):
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 31, in RegistrationView
    authenticated_redirect_url = settings.VERIFY_LOGOUT_URL
NameError: name 'settings' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 7, in <module>
    from user import views as user_views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 26, in <module>
    class RegistrationView(FormValidMessageMixin, CreateView):
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 32, in RegistrationView
    authenticated_redirect_url = settings.VERIFY_LOGOUT_URL
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'VERIFY_LOGOUT_URL'
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 16, in <module>
    url(r'^$', IndexView.as_view(), name='index'),
NameError: name 'IndexView' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 76, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list))
django.template.base.TemplateDoesNotExist: index.html
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 76, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list))
django.template.base.TemplateDoesNotExist: index.html
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 76, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list))
django.template.base.TemplateDoesNotExist: index.html
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 501, in render
    current_app=current_app)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'payg.login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 25, in <module>
    url(r'^account/', include('account.urls')),
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/account/urls.py", line 4, in <module>
    from account import views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/account/views.py", line 26, in <module>
    class AcctStmtListView(AdminOnlyMixin, SetHeadlineMixin, ListView):
NameError: name 'AdminOnlyMixin' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 25, in <module>
    url(r'^account/', include('account.urls')),
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/account/urls.py", line 4, in <module>
    from account import views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/account/views.py", line 26, in <module>
    class AcctStmtListView(LoginRequiredMixin, SetHeadlineMixin, ListView):
  File "/Users/aaron/Documents/github/django-payasyougo/payg/account/views.py", line 29, in AcctStmtListView
    headline = _("Account Statements")
NameError: name '_' is not defined
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 25, in <module>
    url(r'^account/', include('account.urls')),
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/account/urls.py", line 5, in <module>
    from account.forms import (AuthenticationForm, PasswordResetForm, SetPasswordForm,
ImportError: cannot import name 'AuthenticationForm'
Not Found: /index
Internal Server Error: /404/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/views.py", line 14, in handler404
    context_instance=RequestContext(request))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 208, in render_to_string
    t = self.get_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 190, in do_block
    parser.invalid_block_tag(endblock, 'endblock', acceptable_endblocks)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
django.template.base.TemplateSyntaxError: Invalid block tag: 'endblock', expected 'endblock' or 'endblock error_code'
Internal Server Error: /404/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/views.py", line 14, in handler404
    context_instance=RequestContext(request))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 208, in render_to_string
    t = self.get_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 190, in do_block
    parser.invalid_block_tag(endblock, 'endblock', acceptable_endblocks)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
django.template.base.TemplateSyntaxError: Invalid block tag: 'endblock', expected 'endblock' or 'endblock error_code'
Internal Server Error: /404/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/views.py", line 14, in handler404
    context_instance=RequestContext(request))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 208, in render_to_string
    t = self.get_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 190, in do_block
    parser.invalid_block_tag(endblock, 'endblock', acceptable_endblocks)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
django.template.base.TemplateSyntaxError: Invalid block tag: 'endblock', expected 'endblock' or 'endblock error_code'
Internal Server Error: /500/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/views.py", line 21, in handler500
    context_instance=RequestContext(request))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 138, in render_to_string
    raise TemplateDoesNotExist(template_name)
django.template.base.TemplateDoesNotExist: error/500.html
Internal Server Error: /user/login/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 80, in resolve_template
    return loader.get_template(template, using=self.using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
django.template.base.TemplateDoesNotExist: cpanel/auth-forms/login.html
Internal Server Error: /user/login/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 565, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'payg.main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 501, in render
    current_app=current_app)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 575, in reverse
    key)
django.core.urlresolvers.NoReverseMatch: 'payg.main' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/utils/six.py", line 659, in reraise
    raise value
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 575, in reverse
    key)
django.core.urlresolvers.NoReverseMatch: 'main' is not a registered namespace
Not Found: /accounts/profile/
Not Found: /accounts/profile/
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 26, in <module>
    url(r'^user/', include('user.urls')),
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/urls.py", line 16
    'extra_context': {
                   ^
SyntaxError: invalid syntax
Not Found: /accounts/profile/
Not Found: /accounts/profile/
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/aaron/Documents/github/django-payasyougo/payg/payg/urls.py", line 7, in <module>
    from user import views as user_views
  File "/Users/aaron/Documents/github/django-payasyougo/payg/user/views.py", line 59, in <module>
    class UserDetailView(LoginRequiredMixin, SetHeadlineMixin, TemplateView):
NameError: name 'TemplateView' is not defined
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 162, in render
    len_values = len(values)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/utils/functional.py", line 227, in inner
    return func(self._wrapped, *args)
TypeError: object of type 'User' has no len()
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 752, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'user._meta.get_all_field_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 773, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/utils/functional.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/utils/text.py", line 436, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'user._meta.get_all_field_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 871, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 624, in __init__
    var_obj = Variable(var)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 780, in __init__
    var)
django.template.base.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'user._meta.get_all_field_names'
Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 752, in __init__
    self.literal = float(var)
ValueError: could not convert string to float: 'user.__dict__.items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 773, in __init__
    self.literal = mark_safe(unescape_string_literal(var))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/utils/functional.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/utils/text.py", line 436, in unescape_string_literal
    raise ValueError("Not a string literal: %r" % s)
ValueError: Not a string literal: 'user.__dict__.items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 133, in rendered_content
    template = self._resolve_template(self.template_name)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 88, in _resolve_template
    new_template = self.resolve_template(template)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/response.py", line 78, in resolve_template
    return loader.select_template(template, using=self.using)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader.py", line 64, in select_template
    return engine.get_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/defaulttags.py", line 871, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 624, in __init__
    var_obj = Variable(var)
  File "/Users/aaron/Documents/virtualenvs/payg/lib/python3.4/site-packages/django/template/base.py", line 780, in __init__
    var)
django.template.base.TemplateSyntaxError: Variables and attributes may not begin with underscores: 'user.__dict__.items'
